# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - env: ["CGO_ENABLED=0"]
    asmflags: ["all=-trimpath={{.Env.PWD}}"]
    gcflags: ["all=-trimpath={{.Env.PWD}}"]
archives:
  - files: ["none*"]
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brew:
  skip_upload: auto
  github:
    owner: albertrdixon
    name: homebrew-gitlab-cli
  
  folder: Formula
  descrption: "Do a few dumb things with the Gitlab cli, probably not what you want."
  homepage: "https://github.com/albertrdixon/gitlab-cli"
  test: system "#{bin}/gitlab-cli --version"

dockers:
  - dockerfile: docker/Dockerfile
    image_templates:
      - "quay.io/albertrdixon/gitlab-cli:latest"
      - "quay.io/albertrdixon/gitlab-cli:{{ .Tag }}"
      - "quay.io/albertrdixon/gitlab-cli:v{{ .Major }}.{{ .Minor }}"
